# VeinMiner Configuration

settings:
# Maximum number of blocks that can be mined at once (if level system is disabled)
max-blocks: 64

# Durability settings
use-durability-multiplier: true
durability-multiplier: 1.0

# Hunger settings
use-hunger-multiplier: true
hunger-multiplier: 0.1

# Debug mode - enables additional logging
debug: false

# Auto-save interval in minutes (0 to disable)
auto-save-interval: 15

# List of blocks that can be mined with VeinMiner
allowed-blocks:
  - COAL_ORE
  - DEEPSLATE_COAL_ORE
  - IRON_ORE
  - DEEPSLATE_IRON_ORE
  - COPPER_ORE
  - DEEPSLATE_COPPER_ORE
  - GOLD_ORE
  - DEEPSLATE_GOLD_ORE
  - REDSTONE_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DIAMOND_ORE
  - DEEPSLATE_DIAMOND_ORE
  - LAPIS_ORE
  - DEEPSLATE_LAPIS_ORE
  - EMERALD_ORE
  - DEEPSLATE_EMERALD_ORE
  - NETHER_GOLD_ORE
  - NETHER_QUARTZ_ORE
  - ANCIENT_DEBRIS
  - OAK_LOG
  - BIRCH_LOG
  - SPRUCE_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - MANGROVE_LOG
  - CHERRY_LOG
  - CRIMSON_STEM
  - WARPED_STEM

# Permission settings
permissions:
# Whether to require a permission to use VeinMiner
require-permission: true
# The permission node required to use VeinMiner
use-permission: "veinminer.use"

# Level system settings
level-system:
  # Whether to enable the level system
  enabled: true
  # Number of blocks mined to gain 1 XP
  blocks-per-xp: 5
  # XP required for each level (level 1 requires 0 XP)
  xp-per-level:
    1: 0
    2: 100
    3: 250
    4: 500
    5: 1000
    6: 2000
    7: 4000
    8: 8000
    9: 16000
    10: 32000
  # Maximum blocks that can be mined at each level
  max-blocks-per-level:
    1: 8
    2: 16
    3: 24
    4: 32
    5: 48
    6: 64
    7: 96
    8: 128
    9: 192
    10: 256
  # Level up effects settings
  effects:
    # Whether to enable level up effects
    enabled: true
    # Sound effect when leveling up
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
    # Particle effects
    particles:
      enabled: true
      type: TOTEM_OF_UNDYING
      count: 50
      offset-x: 0.5
      offset-y: 1.0
      offset-z: 0.5
      speed: 0.1
    # Potion effects
    potion-effects:
      enabled: true
      regeneration-duration: 5
      regeneration-amplifier: 1
      speed-duration: 10
      speed-amplifier: 0
    # Title message
    title:
      enabled: true
      text: "&6&lLEVEL UP!"
      subtitle: "&eYou are now level &6%level%"
      fade-in: 10
      stay: 70
      fade-out: 20

# Achievement system settings
achievement-system:
# Whether to enable the achievement system
enabled: true

# Economy settings for rewards
economy:
  # Whether to use economy rewards
  enabled: true
  # Command to give money to players (use %player% and %amount% as placeholders)
  give-command: "eco give %player% %amount%"

# List of achievements
achievements:
  # Mining specific blocks
  mine_coal:
    name: "Coal Collector"
    description: "Mine 100 coal ore blocks"
    type: "BLOCK_MINE"
    block: "COAL_ORE,DEEPSLATE_COAL_ORE"
    amount: 100
    rewards:
      money: 100
      items:
        - "COAL:16"

  mine_iron:
    name: "Iron Miner"
    description: "Mine 100 iron ore blocks"
    type: "BLOCK_MINE"
    block: "IRON_ORE,DEEPSLATE_IRON_ORE"
    amount: 100
    rewards:
      money: 200
      items:
        - "IRON_INGOT:8"

  mine_gold:
    name: "Gold Digger"
    description: "Mine 50 gold ore blocks"
    type: "BLOCK_MINE"
    block: "GOLD_ORE,DEEPSLATE_GOLD_ORE"
    amount: 50
    rewards:
      money: 300
      items:
        - "GOLD_INGOT:4"

  mine_diamond:
    name: "Diamond Hunter"
    description: "Mine 25 diamond ore blocks"
    type: "BLOCK_MINE"
    block: "DIAMOND_ORE,DEEPSLATE_DIAMOND_ORE"
    amount: 25
    rewards:
      money: 500
      items:
        - "DIAMOND:2"

  mine_ancient_debris:
    name: "Netherite Prospector"
    description: "Mine 10 ancient debris"
    type: "BLOCK_MINE"
    block: "ANCIENT_DEBRIS"
    amount: 10
    rewards:
      money: 1000
      items:
        - "NETHERITE_SCRAP:1"

  # Total blocks mined
  total_blocks:
    name: "Mining Enthusiast"
    description: "Mine 1,000 blocks with VeinMiner"
    type: "TOTAL_BLOCKS"
    amount: 1000
    rewards:
      money: 250
      items:
        - "DIAMOND_PICKAXE:1"

  total_blocks_advanced:
    name: "Mining Expert"
    description: "Mine 10,000 blocks with VeinMiner"
    type: "TOTAL_BLOCKS"
    amount: 10000
    rewards:
      money: 1000
      items:
        - "NETHERITE_PICKAXE:1"

  # Level achievements
  reach_level_5:
    name: "Apprentice Miner"
    description: "Reach level 5 in VeinMiner"
    type: "LEVEL"
    amount: 5
    rewards:
      money: 500
      items:
        - "EXPERIENCE_BOTTLE:16"

  reach_level_10:
    name: "Master Miner"
    description: "Reach level 10 in VeinMiner"
    type: "LEVEL"
    amount: 10
    rewards:
      money: 2000
      items:
        - "ENCHANTED_GOLDEN_APPLE:1"
        - "DIAMOND:8"

# GUI settings
gui:
  # Whether to show the About section in the main menu
  show-about: true

# Database settings for level system
database:
  # Whether to use MySQL for storing player data
  use-mysql: true
  host: "localhost"
  port: 3306
  # Unterstützt sowohl "database" als auch "name"
  database: "veinminer"
  username: "root"
  password: "test"
  table-prefix: "vm_"
  # Reduce database connection error messages in console
  reduce-logging: true
  # Connection pool settings
  pool:
    # Maximum number of connections in the pool
    max-pool-size: 10
    # Minimum number of idle connections
    min-idle: 2
    # Maximum lifetime of a connection in milliseconds
    max-lifetime: 600000
    # Connection timeout in milliseconds
    connection-timeout: 30000
    # How long to wait before timing out idle connections
    idle-timeout: 300000
    # Time to wait for a connection from the pool
    wait-timeout: 10000

logging:
  # Discord webhook logging
  enable-discord-logging: false
  discord-webhook-url: ""