name: Veinminer
version: '1.1.2'
main: org.bischofftv.veinminer.Veinminer
api-version: '1.21'
description: A plugin that allows players to mine connected blocks of the same type at once.
author: BischoffTV

commands:
  veinminer:
    description: Main command for VeinMiner
    aliases: [vm]
    usage: /veinminer [on|off|toggle|tool|gui|help]
  vmtoggle:
    description: Toggle VeinMiner on or off
    usage: /vmtoggle
  vmlevel:
    description: Check your VeinMiner level
    usage: /vmlevel
  vmsetlevel:
    description: Set a player's VeinMiner level
    usage: /vmsetlevel <player> <level>
    permission: veinminer.admin
  vmsync:
    description: Synchronize VeinMiner data
    usage: /vmsync
    permission: veinminer.admin
  veinminerreload:
    description: Reload VeinMiner configuration
    usage: /veinminerreload
    permission: veinminer.admin
  veinminerabout:
    description: Show information about VeinMiner
    usage: /veinminerabout
  veinminerhelp:
    description: Show VeinMiner help
    usage: /veinminerhelp
  vmadmin:
    description: VeinMiner admin commands
    usage: /vmadmin [debug|reload|sync|stats|bstats]
    permission: veinminer.admin
permissions:
  veinminer.use:
    description: Allows the player to use VeinMiner
    default: true
  veinminer.tool.pickaxe:
    description: Allows the player to use VeinMiner with pickaxes
    default: true
  veinminer.tool.axe:
    description: Allows the player to use VeinMiner with axes
    default: true
  veinminer.tool.shovel:
    description: Allows the player to use VeinMiner with shovels
    default: true
  veinminer.tool.hoe:
    description: Allows the player to use VeinMiner with hoes
    default: true
  veinminer.admin:
    description: Allows access to all VeinMiner admin commands
    default: op
    children:
      veinminer.use: true
      veinminer.tool.pickaxe: true
      veinminer.tool.axe: true
      veinminer.tool.shovel: true
      veinminer.tool.hoe: true